image: ubuntu:vivid

before_script:
  - apt-get update
  - apt-get install -y curl file build-essential unzip

cache:
  paths:
    - $HOME/.cargo
    - $CI_PROJECT_DIR/target

stages:
  - install-rust
  - install-vault
  - build
  - test
  - publish

stable:
  stage: install-rust
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo

beta:
  stage: install-rust
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=beta

nightly:
  stage: install-rust
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly

vault-0.4.1:
  stage: install-vault
  script:
    - VAULT_VERSION=0.4.1 bin/install-vault-release.sh

vault-0.5.0:
  stage: install-vault
  script:
    - VAULT_VERSION=0.5.0 bin/install-vault-release.sh

vault-head:
  stage: install-vault
  script:
    - bin/install-vault-head.sh

build:
  stage: build
  script:
    - cargo build --release --verbose

test:
  stage: test
  script:
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose

publish:
  stage: publish
  only:
    - tags
  script:
    - apt-get update
    - apt-get install -y curl file build-essential
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - mv Cargo.toml.new Cargo.toml
    - cargo build --release --verbose
    - cargo test --verbose
    - cargo package --verbose
    - cargo doc --verbose
    - cargo publish --token "$CRATES_IO_TOKEN"
