image: ubuntu:vivid

before_script:
  - apt-get update
  - apt-get install -y curl file build-essential unzip libssl-dev

cache:
  untracked: true
  paths:
    - $HOME/.cargo
    - $CI_PROJECT_DIR/target

stages:
  - test
  - publish

variables:
  PATH: $HOME/bin:$PATH

test-stable-0.4.1:
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - VAULT_VERSION=0.4.1 bin/install-vault-release.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose

test-stable-0.5.0:
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - VAULT_VERSION=0.5.0 bin/install-vault-release.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose

test-stable-head:
  allow_failure: true
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - bin/install-vault-head.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose



test-beta-0.4.1:
  allow_failure: true
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=beta
    - VAULT_VERSION=0.4.1 bin/install-vault-release.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose

test-beta-0.5.0:
  allow_failure: true
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=beta
    - VAULT_VERSION=0.5.0 bin/install-vault-release.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose

test-beta-head:
  allow_failure: true
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=beta
    - bin/install-vault-head.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose



test-nightly-0.4.1:
  allow_failure: true
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly
    - VAULT_VERSION=0.4.1 bin/install-vault-release.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose

test-nightly-0.5.0:
  allow_failure: true
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly
    - VAULT_VERSION=0.5.0 bin/install-vault-release.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose

test-nightly-head:
  allow_failure: true
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly
    - bin/install-vault-head.sh
    - cargo build --release --verbose
    - vault server -dev > /dev/null 2>&1 &
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
    - cargo test --verbose


publish:
  stage: publish
  only:
    - tags
  script:
    - apt-get update
    - apt-get install -y curl file build-essential
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - mv Cargo.toml.new Cargo.toml
    - cargo build --release --verbose
    - cargo test --verbose
    - cargo package --verbose
    - cargo doc --verbose
    - cargo publish --token "$CRATES_IO_TOKEN"
