image: ubuntu:vivid

before_script:
  - apt-get update
  - apt-get install -y curl file build-essential unzip libssl-dev

cache:
  untracked: true
  key: "$CI_BUILD_NAME"
  paths:
    - $HOME/.cargo
    - $CI_PROJECT_DIR/target

stages:
  - test
  - publish


test-stable-0.4.1:
  script:
    - VAULT_VERSION=0.4.1 bin/install-vault-release.sh
    - $HOME/bin/vault server -dev &
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - cargo build --release --verbose
    - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
    - cargo test --verbose

test-stable-0.5.0:
  script:
    - VAULT_VERSION=0.5.0 bin/install-vault-release.sh
    - $HOME/bin/vault server -dev &
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - cargo build --release --verbose
    - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
    - cargo test --verbose

# test-stable-head:
#   allow_failure: true
#   script:
#     - bin/install-vault-head.sh
#     - $HOME/bin/vault server -dev &
#     - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
#     - cargo build --release --verbose
#     - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
#     - cargo test --verbose



# test-beta-0.4.1:
#   allow_failure: true
#   script:
#     - VAULT_VERSION=0.4.1 bin/install-vault-release.sh
#     - $HOME/bin/vault server -dev &
#     - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=beta
#     - cargo build --release --verbose
#     - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
#     - cargo test --verbose

test-beta-0.5.0:
  allow_failure: true
  script:
    - VAULT_VERSION=0.5.0 bin/install-vault-release.sh
    - $HOME/bin/vault server -dev &
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=beta
    - cargo build --release --verbose
    - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
    - cargo test --verbose

# test-beta-head:
#   allow_failure: true
#   script:
#     - bin/install-vault-head.sh
#     - $HOME/bin/vault server -dev &
#     - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=beta
#     - cargo build --release --verbose
#     - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
#     - cargo test --verbose



# test-nightly-0.4.1:
#   allow_failure: true
#   script:
#     - VAULT_VERSION=0.4.1 bin/install-vault-release.sh
#     - $HOME/bin/vault server -dev &
#     - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly
#     - cargo build --release --verbose
#     - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
#     - cargo test --verbose

test-nightly-0.5.0:
  allow_failure: true
  script:
    - VAULT_VERSION=0.5.0 bin/install-vault-release.sh
    - $HOME/bin/vault server -dev &
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly
    - cargo build --release --verbose
    - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
    - cargo test --verbose

# test-nightly-head:
#   allow_failure: true
#   script:
#     - bin/install-vault-head.sh
#     - $HOME/bin/vault server -dev &
#     - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly
#     - cargo build --release --verbose
#     - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
#     - cargo test --verbose


publish:
  stage: publish
  only:
    - tags
  script:
    - VAULT_VERSION=0.4.1 bin/install-vault-release.sh
    - $HOME/bin/vault server -dev &
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - cargo build --release --verbose
    - VAULT_ADDR=http://127.0.0.1:8200 $HOME/bin/vault token-create -id="test12345"
    - cargo test --verbose
    - cargo package --verbose
    - cargo doc --verbose
    - cargo publish --token "$CRATES_IO_TOKEN"
