addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - unzip
language: rust
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust:
      - nightly
      - beta
    - env: TRAVIS_CARGO_NIGHTLY_FEATURE="" VAULT_BRANCH=head
env:
    - VAULT_VERSION=0.4.1 VAULT_BRANCH=release TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - VAULT_VERSION=0.5.0 VAULT_BRANCH=release TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - VAULT_BRANCH=head TRAVIS_CARGO_NIGHTLY_FEATURE=""
cache:
  apt: true
  rust-download: true
  directories:
    - ~/.cargo
notifications:
  email:
    on_success: never
before_script:
    - export PATH=$HOME/bin:$PATH
    - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
    - vault server -dev &
    - VAULT_ADDR=http://127.0.0.1:8200 ./vault token-create -id="test12345"
install:
  - install-vault-${VAULT_BRANCH}.sh
script:
  - travis-cargo build
  - travis-cargo test
after_success:
  - travis-cargo coveralls --no-sudo
sudo: false
