addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - unzip
language: rust
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust:
      - nightly
      - beta
    - env:
      - VAULT_BRANCH=head TRAVIS_CARGO_NIGHTLY_FEATURE=""
env:
    - VAULT_VERSION=0.4.1 VAULT_BRANCH=release TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - VAULT_VERSION=0.5.0 VAULT_BRANCH=release TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - VAULT_BRANCH=head TRAVIS_CARGO_NIGHTLY_FEATURE=""
cache:
  apt: true
  rust-download: true
  cargo: true
  pip: true
  directories:
    - ~/.cargo
    - $TRAVIS_BUILD_DIR/target
notifications:
  email:
    on_success: never
before_script:
    - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
    - VAULT_ADDR=http://127.0.0.1:8200 vault token-create -id="test12345"
install:
  - bin/install-vault-${VAULT_BRANCH}.sh
  - export PATH=$HOME/bin:$PATH
  - vault server -dev > /dev/null 2>&1 &
script:
  - travis-cargo build
  - travis-cargo test
after_success:
  - travis-cargo coveralls --no-sudo
  - cargo doc --no-deps
  - travis-cargo --only stable doc-upload
sudo: false
