addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - unzip
language: rust
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust:
      - nightly
      - beta
env:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
cache:
  apt: true
  rust-download: true
  directories:
    - ~/.cargo
notifications:
  email:
    on_success: never
before_script:
    - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
    - wget https://releases.hashicorp.com/vault/0.5.0/vault_0.5.0_linux_amd64.zip && unzip vault_0.5.0_linux_amd64.zip
    - ./vault server -dev &
    - VAULT_ADDR=http://127.0.0.1:8200 ./vault token-create -id="test12345"
script:
  - |
      travis-cargo build &&
      travis-cargo test
after_success:
  - travis-cargo coveralls --no-sudo
sudo: false
