[package]
name = "hashicorp_vault"
version = "0.6.1"
authors = [
  "Chris MacNaughton <chmacnaughton@gmail.com>",
  "Christopher Brickley <brickley@gmail.com>"
]
description = "HashiCorp Vault API client for Rust"
license = "MIT"
repository = "https://github.com/chrismacnaughton/vault-rs"

[dependencies]
chrono = "0.2.22"
hyper = "0.9"
log = "0.3"
quick-error = "1.1.0"
rustc-serialize = "0.3"
url = "1.2.1"

[dependencies.clippy]
optional = true
version = "^0.0"

[features]
default = ["vault_0.6.2"]
"vault_0.6.1" = []
"vault_0.6.2" = ["vault_0.6.1"]
