[package]
name = "hashicorp_vault"
version = "0.6.1"
authors = [
  "Chris MacNaughton <chmacnaughton@gmail.com>",
  "Christopher Brickley <brickley@gmail.com>"
]
description = "HashiCorp Vault API client for Rust"
license = "MIT"
repository = "https://github.com/chrismacnaughton/vault-rs"

[dependencies]
chrono = "~0.4"
hyper = "~0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "~0.8"
log = "0.3"
quick-error = "1.1.0"
url = "1.5"

[dependencies.clippy]
optional = true
version = "^0.0"

[features]
default = ["vault_0.6.2"]
"vault_0.6.1" = []
"vault_0.6.2" = ["vault_0.6.1"]
