[package]
authors = ["Chris MacNaughton <chmacnaughton@gmail.com>"]
description = "HashiCorp Vault API client for Rust"
license = "MIT"
name = "hashicorp_vault"
repository = "https://github.com/chrismacnaughton/vault-rs"
version = "0.3.5"

[dependencies]
hyper = "0.9"
log = "0.3"
quick-error = "1.1.0"
rustc-serialize = "0.3"

[dependencies.clippy]
optional = true
version = "^0.0"
