[package]
name = "vault"
version = "0.1.0"
authors = ["Chris MacNaughton <chmacnaughton@gmail.com>"]
description = "HashiCorp Vault API client for Rust"
repository = "https://github.com/chrismacnaughton/vault-rs"
license = "MIT"

[dependencies]
hyper = "~0.7"
rand = "0.3"
log = "0.3"
rustc-serialize = "0.3"
