version: "3"
services: 
  vault:
    image: vault:1.3.3
    container_name: vault
    hostname: vault-docker
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vault
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_LOCAL_CONFIG
    cap_add:
      - IPC_LOCK
    command:
      - vault
      - server
      - -dev-kv-v1